### PR TITLE
Print prettier status.json and jobs.json

### LINKED ISSUE #736: Prettier printing of status.json
I suggest pretty-printing the dumped `status.json` with whitespace, similar to how `jobs.json` is dumped.  
```
 $ wc status.json jobs.json 
    0   717  7852 status.json
 1288  3764 43923 jobs.json
```
(`status.json` is a single line with no \n, very hard to read by a human in a terminal window without `jq` available)

Possible a simple fix, looking at the lines:
https://github.com/equinor/libres/blob/eb8a93b0d6b2b770720d5c273b2647b781f6c655/python/tests/res/job_queue/test_equinor_jobmanager.py#L59
and
https://github.com/equinor/libres/blob/eb8a93b0d6b2b770720d5c273b2647b781f6c655/python/job_runner/reporting/file.py#L184

### PR DESCRIPTION
**Pull request by hnformentin**
**Issue**
Resolves #736

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by sondreso** [comment]
Add to whitelist

**Comment by hnformentin** [comment]
Jenkins test this please

**Comment by sondreso** [comment]
Jenkins test this please

**Review by sondreso — APPROVED** [review]
LGTM!

**Pull request merged**
