### PR TITLE
Runpath to model config

### PR DESCRIPTION
**Pull request by markusdregi**
**Task**
_The keywords PRE_CLEAR_RUNPATH and DELETE_RUNPATH are loaded directly by enkf_main. This needs to be fixed in order to programatically instantiate an instance of enkf_main._

**Approach**
_Move the two keywords into model_config._

**Pre un-WIP checklist**
- [x] Statoil tests pass locally

### CODE REVIEW

**Comment by joakim-hove** [comment]
No - I'm sorry; instead of merging this we should just completely remove the functionality. The ability to configure whether the realisations should be removed or retained in the runpath directory is way to complex - and generally *not used* - people stick with the default behavior of keeping all realisations around.

**Comment by markusdregi** [comment]
@joakim-hove Are we removing both the PRE_CLEAR_RUNPATH and DELETE_RUNPATH options then?

**Comment by joakim-hove** [comment]
> Are we removing both the PRE_CLEAR_RUNPATH and DELETE_RUNPATH options then?

Yes - we just retain the default functionality, which is to *not* remove anything.

**Comment by markusdregi** [comment]
> > Are we removing both the PRE_CLEAR_RUNPATH and DELETE_RUNPATH options then?
>
> Yes - we just retain the default functionality, which is to not remove anything.

What do you mean? All of this functionality was available in enkf_main prior to this PR.. We should either remove the loading of these keywords from enkf_main or follow the path of this PR.

**Comment by joakim-hove** [comment]
> What do you mean? All of this functionality was available in enkf_main prior to this PR.. We should either remove the loading of these keywords from enkf_main or follow the path of this PR.

Sorry - that was not clear. This is about removing, or not removing, simulation folders. When I say:

> Yes - we just retain the default functionality, which is to not remove anything.

I mean that the final application should not remove any simulation folders - period. As for the changes in *code* that implies that the `PRE_CLEAR_RIUNPATH`, `DELETE_RUNPATH` and `KEEP_RUNPATH` keywords should just be removed.

**Comment by markusdregi** [comment]
Aha 👍 Then we agree. I'll get to work then!

**Comment by markusdregi** [comment]
The handling of the two keywords is done in https://github.com/Statoil/libres/pull/62

**Pull request closed without merging**
