### PR TITLE
Slurm driver part 4: extra options

### PR DESCRIPTION
**Pull request by joakim-hove**
**Issue**
This is part of #938

**Approach**
This PR just adds support for multiple options which can be set with the
```
QUEUE_OPTION SLURM  <option> <value>
```
syntax

### CODE REVIEW

**Comment by joakim-hove** [comment]
rebased

**Comment by joakim-hove** [comment]
rebased - again!

**Comment by joakim-hove** [comment]
I think this should be ready?!

**Comment by joakim-hove** [comment]
For the interaction with everest: https://github.com/equinor/everest/pull/1328 it would be very convenient if this could be reviewed and merged now.

**Review by sondreso — APPROVED** [review]
LGTM!

**Pull request merged**
