### PR TITLE
Fix arguments in Forward Model jobs

### LINKED ISSUE #490: Arguments ignored in the ECLIPSE100 forward model?
It looks like the arguments for version and num-cpu in the [ECLIPSE100](https://github.com/equinor/libres/blob/master/share/ert/forward-models/res/ECLIPSE100) is ignored when the job is added.
`ARGLIST <ECLBASE> --version=<VERSION> --num-cpu=<NUM_CPU>`

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
**Issue**
Resolves #490

**Approach**
Change how the arguments are input in the forward model job, otherwise they're ignored as comments. This is still a WIP as the other FM jobs must be updated as well, and the `--ignore-errors` isn't handled yet, i.e. it can't be toggled in the config file.

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Can't say I'm a big fan of how it looks just now, but I do like that it's python argparse that's used in the `run` function.

**Comment by joakim-hove** [comment]
Observe that the comment syntax - i.e. the "--" in this case is a parameter in the c function which parses the job description file, I. E it can be changed

**Comment by lars-petter-hauge** [comment]
Sure, but that would result in every forward model job expecting it to be treated as a comment would throw. Not an issue for internal jobs of course.

There's changes coming towards the [ert config file](https://github.com/equinor/libres/issues/238) itself, perhaps we could evaluate the possibility for these jobs as well to get some deserved attention. Here we could keep in mind the syntax for comments..

**Comment by markusdregi** [comment]
> There's changes coming towards the ert config file itself, perhaps we could evaluate the possibility for these jobs as well to get some deserved attention. Here we could keep in mind the syntax for comments..

I would say that they are a quite natural candidate for `yaml` as well when that train starts to roll... I suggest that we work around the commenting issue until then.

**Comment by markusdregi** [comment]
@lars-petter-hauge Still WIP?

**Comment by lars-petter-hauge** [comment]
retest

**Comment by lars-petter-hauge** [comment]
@markusdregi I've just restarted travis and jenkins now, get those through and I think we're good to go!

**Review by markusdregi — APPROVED** [review]
LGTM

**Pull request merged**
