### PR TITLE
defined ies_enkf functions

### LINKED ISSUE #557: Split IES algorithm into multiple functions
The current IES implementation is 500 lines long. This should be split up into multiple static functions to improve readability and ease the context switching. The function is already split by comments, so that is a good indication of logical pieces to extract...

### PR DESCRIPTION
**Pull request by geirev**
ies_enkf.c is too long, ref https://github.com/equinor/libres/issues/557#issue-437190685
Several code segments are moved to functions stored in ies_enkf_linalg.c

Resolves: #557

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by andreabrambilla** [comment]
ok to test

**Comment by markusdregi** [comment]
@geirev This is a very welcome improvement! :+1:

May I suggest that we move the functions in `ies_enkf_linalg.c` back into `ies_enkf.c`. The motivation for doing so is that we do not expose additional symbols from `libres` by doing it so. You can still declare the prototypes in the header in the top of the file and then the implementation at the bottom to make a separation.

```C
// Imports

static void ies_enkf_linalg_extract_active(const ies_enkf_data_type * data,
                                    const matrix_type * D0,
                                    const matrix_type * Yin,
                                    const matrix_type * Rin,
                                    matrix_type * E,
                                    matrix_type * D,
                                    matrix_type * Y,
                                    matrix_type * R,
                                    FILE * log_fp,
                                    bool dbg);

// .....

void ies_enkf_updateA( void * module_data,
                       matrix_type * A ,      // Updated ensemble A retured to ERT.
                       const matrix_type * Yin ,    // Ensemble of predicted measurements
                       const matrix_type * Rin ,    // Measurement error covariance matrix (not used)
                       const matrix_type * dObs ,   // Actual observations (not used)
                       const matrix_type * Ein ,    // Ensemble of observation perturbations
                       const matrix_type * Din ,    // (d+E-Y) Ensemble of perturbed observations - Y
                       const module_info_type * module_info,
                       rng_type * rng) {
  ies_enkf_data_type * data = ies_enkf_data_safe_cast( module_data );
  // .......

/*
 * IES linalg methods
 */
static void ies_enkf_linalg_extract_active(const ies_enkf_data_type * data,
                                    const matrix_type * D0,
                                    const matrix_type * Yin,
                                    const matrix_type * Rin,
                                    matrix_type * E,
                                    matrix_type * D,
                                    matrix_type * Y,
                                    matrix_type * R,
                                    FILE * log_fp,
                                    bool dbg) {
  // .......
```

**Comment by geirev** [comment]
I see the point, done!

**Review by markusdregi — APPROVED** [review]
Thank you for updating your PR 👍

**Pull request merged**
