### PR TITLE
Bugfixes in enkf_linalg.cpp and matrix.cpp

### PR DESCRIPTION
**Pull request by geirev**
**Task**
Corrected an erroneous index j to i in enkf_linalg_lowrankE.
Also, replace several ugly tabs to spaces.

Then, in matrix.cpp the function matrix_pretty_fprint_submat has a minor bug where it does not print the last indicated column and row.  Also, a \n after the matrix name makes the output even more pretty.

**Approach**
_Short description of the approach_

**Pre un-WIP checklist**
- [ ] Statoil tests pass locally
- [ ] Have completed graphical integration test steps

**Depends on**
* Statoil/libecl#

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by joakim-hove** [comment]
There is a test failure due to the matrix fixup; if you are certain that your approach is correct - please run the test locally and update until it passes before you push a new version of the code.

**Comment by geirev** [comment]
The test was wrong: the returned X from test_initX_subspace_inversion_algorithm and test_initX_enkf_linalg_lowrank_EE should be identical. Now they are.

**Comment by joakim-hove** [comment]
ok to test

**Review by joakim-hove — APPROVED** [review]

**Pull request merged**
