### PR TITLE
cv_enkf_init_update takes extra arg obs_mask.

### PR DESCRIPTION
**Pull request by stefoss23**
**Task**
cv_enkf_init_update takes extra arg obs_mask.

**Pre un-WIP checklist**
- [ ] Statoil tests pass locally
- [ ] Have completed graphical integration test steps

**Depends on**
* Statoil/libecl#

### CODE REVIEW

**Comment by joakim-hove** [comment]
In addition an update is required here: https://github.com/Statoil/libres/blob/master/lib/enkf/enkf_main.cpp#L1109

**Comment by stefoss23** [comment]
Why?

**Comment by joakim-hove** [comment]
> Why?

Because that function is the frontend to actually call the functions you have changed.

**Comment by joakim-hove** [comment]
This is continued & merged here: https://github.com/Statoil/libres/pull/457

**Pull request closed without merging**
