### PR TITLE
Fix signature of enkf_obs_load and add enkf_obs.valid

### PR DESCRIPTION
**Pull request by pgdr**
Fix the signature of `enkf_obs_load` in the cwrap layer in Python.

Also remove a couple of warnings from `ecl_config_init` at the same time refactoring that function from being ~150 lines to ~60.

### CODE REVIEW

**Review by andreabrambilla — APPROVED** [review]

**Comment by joakim-hove** [comment]
This still seems to fail on the internal Jenkins installation :-(

**Comment by pgdr** [comment]
You are right, Joakim.  I deleted my res installation and forgot to turn on Statoil tests ...

Fixed, and Statoil tests pass.

**Comment by pgdr** [comment]
```
100% tests passed, 0 tests failed out of 229

Label Time Summary:
Python                = 211.75 sec
Python:SLOW_1         = 304.06 sec
Python:SLOW_2         = 213.61 sec
Python:StatoilData    =  76.65 sec
SLOW_1                = 148.00 sec
StatoilData           =  49.65 sec

Total Test time (real) = 292.70 sec
/var/jenkins/jenkins-be/workspace/libres-PR
Tested PR: 148 succesfully
Finished: SUCCESS
```

**Comment by joakim-hove** [comment]
Good work!

**Pull request merged**
