### PR TITLE
Added `Held` status to Torque driver

### PR DESCRIPTION
**Pull request by andreabrambilla**
**Issue**
PBS and Torque are supposedly compatible, but PBS also have the `HELD` status which is not present with Torque

**Approach**
Treat `HELD` as `PENDING`

### CODE REVIEW

**Comment by andreabrambilla** [comment]
I can't access the circle ci page from here, if anyone wants to have a look at it and fix the PR feel free to go ahead

**Comment by sondreso** [comment]
test this please

**Comment by sondreso** [comment]
Test this please

**Review by jondequinor — APPROVED** [review]
LGTM, though I did not test running with either driver.

**Comment by andreabrambilla** [comment]
jenkins retest this please

**Pull request merged**
