### PR TITLE
Use num_cpu in job_node constructor used in job_queue_node.py

### PR DESCRIPTION
**Pull request by ManInFez**
num_cpu was not passed on to the c constructor of job_node.

### CODE REVIEW

**Comment by markusdregi** [comment]
Can we have a test please? :)

**Comment by sondreso** [comment]
Could you change the cmake version number in the backport version of this pr ? :)

**Comment by markusdregi** [comment]
Jenkins: Retest this please

**Review by markusdregi — APPROVED** [review]
Looks good to me 👍 Please make a backport of this....

**Pull request merged**
