### PR TITLE
Added stop method to SimualtionContext

### PR DESCRIPTION
**Pull request by joakim-hove**
**Task**
Batch simulator had incorrect documentation string - fixed that.

Added `stop( )`method to `SimulationContext`

**Pre un-WIP checklist**
- [x] Statoil tests pass locally
- [ ] Have completed graphical integration test steps

### CODE REVIEW

**Comment by pgdr** [comment]
The title of this PR seems misleading.  It seems to include a new exposed symbol??

**Comment by pgdr** [comment]
It seems like this feature doesn't actually require exposing this new function out in the header file.

**Comment by joakim-hove** [comment]
Title us misleading yes.

Will look at the header, but as long as it is used from Python I would say it is deeply facto exported and should be in the header?

**Comment by pgdr** [comment]
My point was that you can achieve the same thing _without_ exposing a new symbol.

Either use `queue.killAllJobs()` which seems to do the same, except has a harsher name, or use
`queue._start_user_exit()` and then `queue.isRunning()`.

**Comment by joakim-hove** [comment]
> My point was that you can achieve the same thing without exposing a new symbol.

OK - I see your point; I personally like the new approach based on the `queue_manager` implementation better - the coupling to the actual queue implementation becomes looser. I have updated other call sites in libres to use the new symbol. The `JobQueue.killAllJobs( )` method is still present because it is used from the main ert application, but I would like to change that callsite as well - and then remove the `JobQueue.killAllJobs( )` method (that will have to be in a new PR).

**Pull request merged**
