### PR TITLE
Remove unused classes ArgPack and CThreadPool

### PR DESCRIPTION
**Pull request by jepebe**
Suggestion: The Python classes ArgPack and CThreadPool seems to be unused. There are no references, that I could find, in libres, ERT or Everest. This PR removes these classes with associated tests.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by dotfloat** [comment]
Can they be removed in the C code?

**Comment by dotfloat** [comment]
Jenkins please test this

**Review by pinkwah — APPROVED** [review]
LGTM

**Comment by pinkwah** [comment]
Jenkins test this please

**Comment by pinkwah** [comment]
Jenkins test this please

**Pull request merged**
