### PR TITLE
Slurm prep1

### PR DESCRIPTION
**Pull request by joakim-hove**
**Issue**
Part of: #938

**Approach**
This PR just contains two small drive-by commits from the very first start of the slurm implementation.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by sondreso** [comment]
Add to whitelist

**Comment by joakim-hove** [comment]
Is the failure on "Equinor Jenkins build" for real - or is this a false (positive|negative)?

**Comment by sondreso** [comment]
The error message is pasted below, but we have had some problems with full disks on the jenkins nodes lately, and my guess is that is what is causing the problem. I will see if I can get the disks cleared! 
```
93/146 Test  #97: enkf_forward_init_GEN_PARAM_FALSE .........***Exception: Child aborted  0.19 sec


Abort called from: util_make_path (/tmp/tmp.8A6zrlNjlK/libecl/lib/util/util.c:4719) 

Error message: util_make_path: failed to make directory:/tmp/jenkins/test/main/37184319 - aborting
: File exists(17) 



--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                              in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/util_abort_gnu.c:173
 #01 util_make_path(..)                                                            in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/util.c:4719
 #02 _ZN3ecl4util8TestAreaC1ERKSsb(..)                                             in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/test_work_area.cpp:172
 #03 main(..)                                                                      in /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3303
 #04 __libc_start_main(..)                                                         in ???
 #05 ???? 
--------------------------------------------------------------------------------


Abort called from: util_abort_signal (/tmp/tmp.8A6zrlNjlK/libecl/lib/util/util.c:4448) 

Error message: Program received signal:6



--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                              in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/util_abort_gnu.c:173
 #01 ???? 
 #02 gsignal(..)                                                                   in ???
 #03 abort(..)                                                                     in ???
 #04 util_abort__(..)                                                              in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/util_abort_gnu.c:329
 #05 util_make_path(..)                                                            in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/util.c:4719
 #06 _ZN3ecl4util8TestAreaC1ERKSsb(..)                                             in /tmp/tmp.8A6zrlNjlK/libecl/lib/util/test_work_area.cpp:172
 #07 main(..)                                                                      in /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3303
 #08 __libc_start_main(..)                                                         in ???
 #09 ???? 
--------------------------------------------------------------------------------
```

**Comment by joakim-hove** [comment]
> The error message is pasted below, but we have had some problems with full disks on the jenkins nodes lately, and my guess is that is what is causing the problem. I will see if I can get the disks cleared!

OK thank you; I will assume the disk full situation is the culprit and sit quite still.

**Comment by sondreso** [comment]
Retest this please

**Review by sondreso — APPROVED** [review]
LGTM!

**Pull request merged**
