### PR TITLE
Intruduce max_runtime and runtime in job_queue_node on python layer

### LINKED ISSUE #576: MAX_RUNTIME not working?
Users have reported `MAX_RUNTIME` to not work properly over `lsf`. I suggest to modify the poly case so that the job sleeps for a long time, add `MAX_RUNTIME 2` and see whether we can reproduce.

### PR DESCRIPTION
**Pull request by ManInFez**
resolves https://github.com/equinor/ert/issues/576

### CODE REVIEW

**Comment by wouterjdb** [comment]
FYI: Also the `STOP_LONG_RUNNING` keyword didn't actually trigger the kill command. Not sure if that is solved with this or that it should be part of this PR at all.

**Comment by markusdregi** [comment]
> FYI: Also the STOP_LONG_RUNNING keyword didn't actually trigger the kill command. Not sure if that is solved with this or that it should be part of this PR at all.

That will be a new issue ;)

**Review by markusdregi — APPROVED** [review]
:rocket:

**Comment by wouterjdb** [comment]
FYI: I build a new environment with the latest ERT master and now realizations are nicely being killed again using the `MAX_RUNTIME` keyword. Thanks for the quick response! Moving on to the next iteration as we speak.... without manually killing realizations, so nice.... 🎉

**Comment by markusdregi** [comment]
@wouterjdb Thanks for testing and reporting 👍

**Pull request merged**
