### PR TITLE
Bump libecl to 2.9.2rc1

### PR DESCRIPTION
**Pull request by sondreso**
Bump libecl to 2.9.2rc1

### CODE REVIEW

**Comment by sondreso** [comment]
Jenkins test this please

**Review by oyvindeide — DISMISSED** [review]

**Comment by oyvindeide** [comment]
I am guessing the failed job is not related to this PR?

**Comment by sondreso** [comment]
Thanks! 
Nope, same error as @jepebe and the new release is experiencing, trying to debug...

**Comment by sondreso** [comment]
Jenkins test this please

**Review by hnformentin — APPROVED** [review]

**Comment by jepebe** [comment]
Not necessarily part of this PR but would it make sense to have the `wait_until()` print an error message or, alternatively, wrap the inner assertion of the test in a `TimeoutAssertionError` instead? Would have made the bug easier to diagnose since it would actually pinpoint the reason for failing.

**Comment by sondreso** [comment]
> Not necessarily part of this PR but would it make sense to have the `wait_until()` print an error message or, alternatively, wrap the inner assertion of the test in a `TimeoutAssertionError` instead? Would have made the bug easier to diagnose since it would actually pinpoint the reason for failing.

Yes, I think that is a very good idea! Will merge this so it's not blocking everything, but also created this issue: https://github.com/equinor/libres/issues/1009

**Pull request merged**
