### PR TITLE
Easier Python testing

### PR DESCRIPTION
**Pull request by markusdregi**
This is an attempt at making running the Python tests of libres more vanilla.

**Goal**
Have a easy and short procedure to be able to run the libres tests. As of now (after the changes in the PR) the GitHub action pipeline is running the following:

```
# Preferable inside a virtual env with rather new pip
git clone https://github.com/equinor/libres.git
pip install .
pip install -r test_requirements.txt
pytest
```

**Approach**
Move all the Python tests from `python/tests` to `tests` to prevent `pytest` from discovering the source code within the `python`-folder and use the installed version without the crazy symlinking currently done in the CI. This is a massive number of files moved, but besides that the footprint is quite small. Notice that this is getting closer to a `src` - `tests` layout of the repository, which is an often recommended method of preventing the accidental pick up of source code over installed code.

**Remains**
- Separate the movement of files into a separate commit (this will not make the tests runnable on the first commit, so maybe not?)
- ~~Update Jenkins scripts!~~
- ~~Update README~~

### CODE REVIEW

**Comment by joakim-hove** [comment]
Thanks for looking into this.

```bash
bash% pip install .
....
ert 2.17.2.dev9+ga97dd336 requires alembic, which is not installed.
ert 2.17.2.dev9+ga97dd336 requires PyQt5, which is not installed.
Successfully installed equinor-libres-8.0.0b1.dev2+g7ad70915a
```
Don't really understand the warnings about ert packages?


```bash
bash% pip install -r test_requirements.txt
bash% pytest
(venv) hove@ws:/tmp/libres$ pytest
============================================================= test session starts ==============================================================
platform linux -- Python 3.7.3, pytest-5.2.4, py-1.8.0, pluggy-0.13.0
rootdir: /tmp/libres
collected 388 items / 4 errors / 384 selected                                                                                                  

==================================================================== ERRORS ====================================================================
___________________________________________ ERROR collecting tests/job_runner/test_event_reporter.py ___________________________________________
ImportError while importing test module '/tmp/libres/tests/job_runner/test_event_reporter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/job_runner/test_event_reporter.py:4: in <module>
    from job_runner.reporting import Event
E   ImportError: cannot import name 'Event' from 'job_runner.reporting' (/home/hove/work/ERT/install/lib/python3.7/site-packages/job_runner/reporting/__init__.py)
____________________________________________ ERROR collecting tests/job_runner/test_job_dispatch.py ____________________________________________
ImportError while importing test module '/tmp/libres/tests/job_runner/test_job_dispatch.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/job_runner/test_job_dispatch.py:16: in <module>
    from job_runner.cli import main, _setup_reporters
E   ImportError: cannot import name '_setup_reporters' from 'job_runner.cli' (/home/hove/work/ERT/install/lib/python3.7/site-packages/job_runner/cli.py)
______________________________________________ ERROR collecting tests/res/enkf/test_res_config.py ______________________________________________
tests/res/enkf/test_res_config.py:164: in <module>
    {ConfigKeys.NAME: QueueConfig.LSF_QUEUE_NAME_KEY, ConfigKeys.VALUE: "mr"},
E   AttributeError: type object 'QueueConfig' has no attribute 'LSF_QUEUE_NAME_KEY'
________________________________________________ ERROR collecting tests/res/fm/test_rms_run.py _________________________________________________
ImportError while importing test module '/tmp/libres/tests/res/fm/test_rms_run.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/res/fm/test_rms_run.py:29: in <module>
    from res.fm.rms import RMSRun, RMSRunException
E   ImportError: cannot import name 'RMSRunException' from 'res.fm.rms' (/home/hove/work/ERT/install/lib/python3.7/site-packages/res/fm/rms/__init__.py)
=============================================================== warnings summary ===============================================================
tests/res/config/test_config.py:28
  /tmp/libres/tests/res/config/test_config.py:28: PytestCollectionWarning: cannot collect test class 'TestConfigPrototype' because it has a __init__ constructor (from: tests/res/config/test_config.py)
    class TestConfigPrototype(ResPrototype):

/home/hove/work/ERT/install/lib/python3.7/site-packages/_pytest/mark/structures.py:325
  /home/hove/work/ERT/install/lib/python3.7/site-packages/_pytest/mark/structures.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.unstable - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

/home/hove/work/ERT/install/lib/python3.7/site-packages/ecl/util/test/test_run.py:30
  /home/hove/work/ERT/install/lib/python3.7/site-packages/ecl/util/test/test_run.py:30: PytestCollectionWarning: cannot collect test class 'TestRun' because it has a __init__ constructor (from: tests/res/run/test_run.py)
    class TestRun(object):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================= 3 warnings, 4 error in 1.52s =========================================================

**Comment by markusdregi** [comment]
That is odd @joakim-hove ! Did you run it inside a virtual env? Could it be that you have some "old" version of ert installed? Alembic was recently introduced as a dependency in ERT, so that is why I'm thinking it might be an outdated version in your environment...

**Comment by joakim-hove** [comment]
OK - now I made *very certain* it was all in a clean environment; and wham bang this worked:
```
#!/bin/bash

rm -rf venv
rm -rf libres

unset PYTHONPATH
unset LD_LIBRARY_PATH
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip

git clone git@github.com:markusdregi/libres
pushd libres
git checkout ease_py_testing
pip install .
pip install -r test_requirements.txt
pytest
popd
```

Good!

**Comment by markusdregi** [comment]
Excellent! Thanks for testing @joakim-hove! I'll finish of this PR as soon as possible...

**Review by ManInFez — APPROVED** [review]
:bacon:

**Pull request merged**
