### PR TITLE
WIP Refactor cmake

### PR DESCRIPTION
**Pull request by jokva**

### CODE REVIEW

**Comment by joakim-hove** [comment]
Good if include the spirit of #12 into this PR.

**Comment by joakim-hove** [comment]
Looking forward to start using the shiny and new cmake configuration.

**Comment by jokva** [comment]
https://github.com/Statoil/libres/pull/12 will be included for sure, I'll get to it first thing tomorrow.

**Comment by joakim-hove** [comment]
A sorry - wrong PR.

**Comment by joakim-hove** [comment]
Works on RH6 - in she goes!

**Review by joakim-hove — APPROVED** [review]

**Pull request merged**
