### PR TITLE
Drop support for Python versions < 3.6

### PR DESCRIPTION
**Pull request by sondreso**
#1000 :tada: 
Drop support for Python versions below 3.6.

**Approach**
Remove code targeting Python < 3.6. In addition this PR also switches to Github actions for testing, so it will require admin merge and switching required tests. Adds testing for Python 3.7 and 3.8 on Ubuntu.

### CODE REVIEW

**Comment by ManInFez** [comment]
Doesnt INSTALL_ERT_LEGACY also go out the door with this PR? It was only installed with py2 if I remember correctly

**Comment by ManInFez** [comment]
I am quit amazed this line is there:
https://github.com/equinor/libres/blob/fb1dce9749445df7aaee66c99dced542b79336fd/share/ert/gui/help/config/keywords/config_help.py#L1

**Comment by ManInFez** [comment]
I dont know what this means:
https://github.com/equinor/libres/blob/fb1dce9749445df7aaee66c99dced542b79336fd/python/res/util/ui_return.py#L50

**Review by pinkwah — APPROVED** [review]
:crab: LEGACY IS GONE :crab:

**Pull request merged**
