### PR TITLE
Row scale prepare

### PR DESCRIPTION
**Pull request by joakim-hove**
**Issue**
Small preparations/simplifications for #1070

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by joakim-hove** [comment]
Can this be merged?

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by sondreso** [comment]
We will get this reviewed before end of this week :slightly_smiling_face:

**Comment by sondreso** [comment]
Sorry for the late response!

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by joakim-hove** [comment]
Would it be possible to post the jenkins failure here?

**Comment by sondreso** [comment]
Jenkins is failing during pytest collection, due to a weird permission error on an internal test data file. There have recently been changes to the test-data structure on master, could you try to rebase and see if that fixes the problem?

**Comment by joakim-hove** [comment]
OK - I have rebased :crossed_fingers:

**Comment by sondreso** [comment]
Jenkins test this please

**Review by sondreso — APPROVED** [review]
:gift: :santa:

**Pull request merged**
