### PR TITLE
Remove old EXIT file (same is reported in ERROR file)

### LINKED ISSUE #702: Remove the old EXIT file
Currently the job runner dumps both an EXIT and an ERROR file on errors. The EXIT file is old and deprecated and should be removed.

Depends on: https://github.com/equinor/libres/pull/653

### PR DESCRIPTION
**Pull request by hnformentin**
**Issue**
Resolves #702

### CODE REVIEW

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by hnformentin** [comment]
Jenkins test this please

**Review by joakim-hove — COMMENTED** [review]
This file is used in the c layer as well

**Comment by hnformentin** [comment]
Jenkins test this please

**Review by sondreso — APPROVED** [review]

**Comment by sondreso** [comment]
This looks good! Could you rebase one more time so we are sure we are running with the latest changes? Also we need to remember to bump the major version of libres when this change is included.

**Pull request merged**
