### PR TITLE
Log RANDOM_SEED

### LINKED ISSUE #309: Seed is not logged to log-files nor terminal
The seed is no longer logged to neither the terminal nor the log-files with the default log settings! That should change back...

### PR DESCRIPTION
**Pull request by jondequinor**
**Issue**
Resolves https://github.com/equinor/ert/issues/309

**Approach**
Reinstate https://github.com/equinor/libres/commit/82954b52b5adf94eb2e19465708558c1935d05b3#diff-57ee1e547e5d8ce7df030c6a42822abbL160

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by andreabrambilla** [comment]
jenkins test this please

**Comment by andreabrambilla** [comment]
@jondequinor I'm adding you to the whitelist on jenkins, you should not get that message from abrautomate anymore

**Review by andreabrambilla — APPROVED** [review]
:+1:

**Pull request merged**
