### PR TITLE
[WIP] Remove uses of TestAreaContext from python tests

### PR DESCRIPTION
**Pull request by pinkwah**

### CODE REVIEW

**Comment by pinkwah** [comment]
Jenkins test this please

**Comment by pinkwah** [comment]
Jenkins test this please

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by sondreso** [comment]
This PR is closed due to inactivity. Feel free to rebase and adapt to the changes that have been introduced (mainly pip installable libres and black formatting), and reopen the PR :smile:

**Pull request closed without merging**
